### PR TITLE
Added GlobalPlatform SCP11B Secure Channel Protocol Applet and Java Test Client.

### PR DESCRIPTION
**Pull request by ThothTrustCom**
Added GP-SCP11B applet and test client.

### CODE REVIEW

**Comment by petrs** [comment]
@ThothTrustCom thnak you for this important addition - a lot of work, can't wait to play with it! 

However, this curated list contains only links to repositories, not the whole code. Would it be possible to create item like this under section 'Library code', ordered lexicographically?
```
- [GlobalPlatform SCP11B Secure Channel protocol ](https://github.com/ThothTrustCom/SCP11B)    ![stars](https://img.shields.io/github/stars/ThothTrustCom/SCP11B.svg?style=social) ![lastcommit](https://img.shields.io/github/last-commit/ThothTrustCom/SCP11B.svg) ![numcontributors](https://img.shields.io/github/contributors-anon/ThothTrustCom/SCP11B.svg) 
  <br>
Implementation of GlobalPlatform SCP11B Secure Channel protocol and Java Test Client
```

**Comment by petrs** [comment]
@ThothTrustCom hello - shall I create the entry myself? No problem with that, I just wanted to give you credit for doing that

**Comment by thotheolh** [comment]
Please proceed to create entry. Currently busy.

**Comment by petrs** [comment]
ok, done - thank you for the project itself!

**Pull request closed without merging**
